### ISSUE TITLE
extraneous character

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/william-wordsworth_lyrical-ballads#2]
https://github.com/standardebooks/william-wordsworth_samuel-taylor-coleridge_lyrical-ballads/blob/38ebfac7acd469a3d472605f5d900cb9d9a7f74c/src/epub/text/volume-1.xhtml#L894

"And all the autumn ’twas\ his only play" <= slash after "twas"

**Comment by acabal** [comment]
Thanks, this should be fixed now!
