### ISSUE TITLE
OCR typo "tiver" ("river")

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/william-wordsworth_lyrical-ballads#3]
https://github.com/standardebooks/william-wordsworth_samuel-taylor-coleridge_lyrical-ballads/blob/7785fe6a8922aadec7c902a39cbdcdab0134b54f/src/epub/text/endnotes.xhtml#L61

https://github.com/standardebooks/william-wordsworth_samuel-taylor-coleridge_lyrical-ballads/blob/7785fe6a8922aadec7c902a39cbdcdab0134b54f/src/epub/text/endnotes.xhtml#L86

**Comment by acabal** [comment]
Thanks, these should be fixed now!
